### PR TITLE
Easy svg usage with dot notation support.

### PR DESCRIPTION
**Pull request by mertasan**
```blade
<x-input leading-icon="hero.home" />
<x-input leading-icon="hero.outline.home" />

<x-input trailing-icon="hero.home" />
<x-input trailing-icon="hero.outline.home" />
```

Sorry, I didn't have time to write the tests.

### CODE REVIEW

**Review by rawilk — CHANGES_REQUESTED** [review]
Please format the code in `HasAddons.php` & `FormComponentsServiceProvider.php` to match the style of the package, i.e. use single quotes instead of double quotes, and add spacing between blocks of code.

**Comment by rawilk** [comment]
@mertasan Thanks for taking the time to create a PR. I do like the idea of this, however before I merge I just ask that you update the formatting of a few files to closer match the style of the package as noted in my review. Normally, php cs fixer should have automatically formatted it when committed, but there was an error that was preventing the GH action to finish running.

**Comment by rawilk** [comment]
Also, FYI I am working on a new major release of the package, which may impact some changes you made in this PR, so you may need to adjust accordingly.

**Comment by mertasan** [comment]
I cloned the package. I've made many changes and additions on local. I will fulfill your demands today. Then I'll create a few PR for other changes.

Thank you

**Comment by mertasan** [comment]
@rawilk please let me know if other changes are required.

**Comment by rawilk** [comment]
After thinking about it, I think I'm going to pass on this for now. A lot has changed in the package, and I'd also prefer not to have to maintain this in the future since I don't personally render the icons like that.

**Pull request closed without merging**
